classname: pipelines.dn_looking_adcp.pipeline.DnLookingADCP

triggers:
  - .*winriver*\.PD0

retriever:
  path: pipelines/dn_looking_adcp/config/retriever.yaml

dataset:
  path: pipelines/dn_looking_adcp/config/dataset.yaml

quality:
  path: pipelines/dn_looking_adcp/config/quality.yaml

storage:
  path: shared/storage.yaml
