# Conda environment for developing tsdat pipelines

name: adcp-pipelines
channels:
  - conda-forge
dependencies:
  - python=3.10
  - hdf5
  - pytables
  - pip
  - pip:
      - "-r requirements-dev.txt"
