classname: pipelines.dn_looking_sontek.pipeline.DnFacingSontek

triggers:
  - .*\b[0-9]{14}\b.*\.vel

retriever:
  path: pipelines/dn_looking_sontek/config/retriever.yaml

dataset:
  path: pipelines/dn_looking_sontek/config/dataset.yaml

quality:
  path: pipelines/dn_looking_sontek/config/quality.yaml

storage:
  path: shared/storage.yaml
