classname: tsdat.io.retrievers.DefaultRetriever
readers:
  .*:
    classname: pipelines.dn_looking_sontek.readers.ReadSontek

coords:
  time:
    name: Date/Time
    data_converters:
      - classname: tsdat.io.converters.StringToDatetime
        format: "%d/%m/%Y %H:%M:%S %p"
        timezone: US/Alaska
  range:
    name: range

data_vars:
  vel_east:
    name: vel_east
  vel_north:
    name: vel_north
  vel_up:
    name: vel_up
  vel_err:
    name: vel_err
  U_mag:
    name: U_mag
  U_dir:
    name: U_dir
  bin_depth:
    name: bin_depth
  number:
    name: "Sample #"
  # frequency:
  #   name: Frequency (MHz)
  # profile_type:
  #   name: Profile Type
  depth:
    name: Depth (m)
  cell_size:
    name: Cell Size (m)
  blank_dist:
    name: Cell Start (m)
  latitude:
    name: Latitude (deg)
  longitude:
    name: Longitude (deg)
  heading:
    name: Heading (deg)
  pitch:
    name: Pitch (deg)
  roll:
    name: Roll (deg)
  dist_bt:
    name: BT Depth (m)
  dist_alt:
    name: VB Depth (m)
