from typing import Dict, Union
from pydantic import BaseModel, Extra
import xarray as xr
import mhkit.dolfyn as dolfyn
from mhkit.dolfyn.adp import api
from tsdat import DataReader


class WinRiver2ADCPReader(DataReader):
    class Parameters(BaseModel, extra=Extra.forbid):
        depth_offset: float = 0.5  # instrument depth below the water surface
        magnetic_declination: float = 0

    parameters: Parameters = Parameters()

    def read(self, input_key: str) -> Union[xr.Dataset, Dict[str, xr.Dataset]]:
        """-------------------------------------------------------------------
        Reads binary files generated by Teledyne WinRiver2 software. These
        files automatically contain all data recieved by the GPS.

        Args:
            filename (str): The path to the ADCP file to read in.

        Returns:
            xr.Dataset: An xr.Dataset object
        -------------------------------------------------------------------"""

        ds = dolfyn.read(input_key)

        # Set depth below water surface

        api.clean.set_range_offset(ds, self.parameters.depth_offset)
        ds["depth"] = ds.attrs["range_offset"] + ds["dist_bt"].mean("beam")

        # Rotate to Earth coordinates
        if not ds.coord_sys == "ship":
            dolfyn.set_declination(ds, self.parameters.magnetic_declination)
            dolfyn.rotate2(ds, "earth")

        return ds
