attrs:
  # https://ioos.github.io/ioos-metadata/ioos-metadata-profile-v1-2.html
  # https://wiki.esipfed.org/Attribute_Convention_for_Data_Discovery_1-3
  # Dataset Description
  conventions: "CD-1.6, ACDD-1.3, IOOS-1.2"
  featureType: timeseries
  id: SigVM_102582
  infoURL: https://www.osti.gov/biblio/1842840
  license: Freely Distributed
  naming_authority: gov.pnnl.sequim
  standard_name_vocabulary: CF Standard Name Table v79

  title: Vessel-mounted ADCP at PNNL-Sequim
  description: >-
    A Nortek Signature 1000 kHz was mounted on the R/V Desdemona to gather spatial
    measurements of current velocity across the entrance to Sequim Bay. The instrument
    was mounted on a pole on the starboard side of the vessel, 0.5 m below waterline.
    The instrument is measuring water-track, bottom-track, altimeter at a sampling rate
    of 2 Hz, integrated with GPS data from an Advanced Navigation Compass GNSS, which is
     saved in a separate datafile.
  keywords: Sequim, data, marine, channel, water velocity, water direction, flows
  # Attribution
  creator_country: USA
  #creator_email:
  creator_institution: Pacific Northwest National Laboratory (PNNL) - Sequim
  creator_institution_url: https://www.pnnl.gov/
  creator_sector: other
  creator_type: institution
  creator_url: https://www.pnnl.gov/
  institution: Pacific Northwest National Laboratory (PNNL)
  publisher_country: USA
  #publisher_email:
  publisher_institution: Pacific Northwest National Laboratory (PNNL) - Sequim
  publisher_url: https://www.pnnl.gov/

  # Platform and Instrument
  platform: boat # or "unmanned_surface_vehicle"
  platform_name: R/V Desdemona # or ASV Jonesy
  platform_vocabulary: https://mmisw.org/ont/ioos/platform
  instrument: In Situ/Laboratory Instruments > Current/Wind Meters > Current Meters
  instrument_vocabulary: GCMD Instrument Keywords #https://gcmd.earthdata.nasa.gov/KeywordViewer/
  make_model: Nortek Signature VM Coastal 1000 kHz

  # Geospatial and Time
  geospatial_bounds:
    POLYGON ((48.0804 -123.0449, 48.0804 -123.0426, 48.0787 -123.0426, 48.0787
    -123.0426, 48.0804 -123.0449)
  geospatial_bounds_crs: "EPSG:4326"
  time_coverage_start: "2022-05-18T21:28:46"
  time_coverage_duration: "01:00:00"
  time_coverage_resolution: "00:00:00.500"

  # TSDAT specific parameters
  location_id: asv
  dataset_name: sigvm
  data_level: b1

  # Pipeline specific parameters
  vel_bt_correction: 1 # Use bottom track to correct velocity measurements?
  vel_gps_correction: 1 # Or use GPS? (Or both?)
  use_alt_depth: 1 # Use altimeter measurements to track depth?
  use_bt_depth: 0 # Or bottom track range? (Or neither?)

coords:
  time:
    dims: [time]
    dtype: datetime64[ms]
    attrs:
      units: Seconds since 1970-01-01 00:00:00 UTC
      long_name: Time
      standard_name: time
      timezone: UTC
      description: "Timestamp for data generated by ADCP beams 1-4"
      coverage_content_type: coordinate
  time_bt:
    dims: [time_bt]
    dtype: datetime64[ms]
    attrs:
      units: Seconds since 1970-01-01 00:00:00 UTC
      long_name: Bottom Track Timestamp
      standard_name: time
      timezone: UTC
      description: "Timestamp for bottom track data generated by ADCP beams 1-4"
      coverage_content_type: coordinate
  time_echo:
    dims: [time_echo]
    dtype: datetime64[ms]
    attrs:
      units: Seconds since 1970-01-01 00:00:00 UTC
      long_name: Echo Sounder Timestamp
      standard_name: time
      timezone: UTC
      description: 'Timestamp for echo sounder data generated by "5th" ADCP beam'
      coverage_content_type: coordinate
  time_gps:
    dims: [time_gps]
    dtype: datetime64[ns]
    attrs:
      units: Seconds since 1970-01-01 00:00:00 UTC
      coverage_content_type: coordinate
      long_name: Time
      standard_name: time
  range:
    dims: [range]
    dtype: float32
    attrs:
      description: "Distance to the center of each depth bin"
      long_name: Profile Range
      units: m
      coverage_content_type: coordinate
  range_echo:
    dims: [range_echo]
    dtype: float32
    attrs:
      description: "Echo sounder distance to the center of each depth bin"
      long_name: Profile Range
      units: m
      coverage_content_type: coordinate
  dir:
    dims: [dir]
    dtype: str
    attrs:
      long_name: Reference Frame
      units: "1"
      coverage_content_type: coordinate
  beam:
    dims: [beam]
    data: [1, 2, 3, 4]
    dtype: int32
    attrs:
      long_name: Beam Reference Frame
      units: "1"
      coverage_content_type: coordinate
  inst:
    dims: [inst]
    dtype: str
    attrs:
      long_name: Instrument Reference Frame
      units: "1"
      coverage_content_type: coordinate
  earth:
    dims: [earth]
    dtype: str
    attrs:
      long_name: Earth Reference Frame
      units: "1"
      coverage_content_type: coordinate

data_vars:
  vel:
    dims: [dir, range, time]
    dtype: float32
    attrs:
      long_name: Sea Water Velocity
      units: m/s
      valid_min: -3
      valid_max: 3
  amp:
    dims: [beam, range, time]
    dtype: float32
    attrs:
      long_name: Acoustic Signal Amplitude
      standard_name: signal_intensity_from_multibeam_acoustic_doppler_velocity_sensor_in_sea_water
      units: dB
  corr:
    dims: [beam, range, time]
    dtype: int32
    attrs:
      long_name: Acoustic Signal Correlation
      standard_name: beam_consistency_indicator_from_multibeam_acoustic_doppler_velocity_profiler_in_sea_water
      units: "%"
  echo:
    dims: [beam, range_echo, time]
    dtype: float32
    attrs:
      long_name: Echo Sounder
      standard_name: echo_sounder_signal_intensity
      units: dB

  U_mag:
    dims: [range, time]
    dtype: float32
    attrs:
      long_name: Water Speed
      standard_name: sea_water_speed
      units: m/s
      valid_min: -3
      valid_max: 3
  U_dir:
    dims: [range, time]
    dtype: float32
    attrs:
      long_name: Water Direction
      standard_name: sea_water_to_direction
      units: degrees

  vel_bt:
    dims: [dir, time_bt]
    dtype: float32
    attrs:
      long_name: Bottom Track Velocity
      standard_name: platform_velocity
      units: m/s
      valid_min: -10
      valid_max: 10
  dist_bt:
    dims: [beam, time_bt]
    dtype: float32
    attrs:
      long_name: Bottom Track Depth
      standard_name: depth_below_platform
      units: m
  fom_bt:
    dims: [dir, time_bt]
    dtype: uint16
    attrs:
      units: "1"
      long_name: Figure of Merit
      coverage_content_type: physicalMeasurement

  le_dist_alt:
    dims: [time]
    dtype: float32
    attrs:
      long_name: Altimeter Range (Leading Edge Algorithm)
      standard_name: altimeter_range
      units: m
  le_quality_alt:
    dims: [time]
    dtype: int32
    attrs:
      long_name: Altimeter Quality (Leading Edge Algorithm)
      units: dB
  ast_dist_alt:
    dims: [time]
    dtype: float32
    attrs:
      long_name: Altimeter Range (Acoustic Surface Tracking)
      standard_name: altimeter_range
      units: m
  ast_quality_alt:
    dims: [time]
    dtype: int32
    attrs:
      long_name: Altimeter Quality (Acoustic Surface Tracking)
      units: dB
  ast_offset_time_alt:
    dims: [time]
    dtype: float32
    attrs:
      description: Altimeter offset from `time`
      units: s
  pressure_alt:
    dims: [time]
    dtype: float32
    attrs:
      long_name: Altimeter Pressure
      standard_name: sea_water_pressure
      units: dbar

  depth:
    dims: [time]
    dtype: float32
    attrs:
      long_name: Depth
      standard_name: depth_below_platform
      units: m
      positive: down
  heading:
    dims: [time]
    dtype: float32
    attrs:
      long_name: Heading
      standard_name: platform_orientation
      units: deg
      valid_min: 0
      valid_max: 360
  pitch:
    dims: [time]
    dtype: float32
    attrs:
      long_name: Pitch
      standard_name: platform_pitch
      units: deg
      valid_min: -180
      valid_max: 180
  roll:
    dims: [time]
    dtype: float32
    attrs:
      long_name: Roll
      standard_name: platform_roll
      units: deg
      valid_min: -180
      valid_max: 180
  orientmat:
    dims: [earth, inst, time]
    dtype: float32
    attrs:
      description: Earth (ENU) to instrument (XYZ) orientation matrix
      long_name: Orientation Matrix
      units: "1"
  beam2inst_orientmat:
    dims: [beam, inst]
    dtype: float
    attrs:
      description: "Beam to instrument orientation matrix"
      units: "1"
  speed_of_sound:
    dims: [time]
    dtype: float32
    attrs:
      long_name: Speed of Sound
      standard_name: speed_of_sound_in_sea_water
      units: m/s
  pressure:
    dims: [time]
    dtype: float32
    attrs:
      long_name: Pressure
      standard_name: sea_water_pressure
      units: dbar
  temperature:
    dims: [time]
    dtype: float32
    attrs:
      long_name: Temperature
      standard_name: sea_water_temperature
      units: degC

  transmit_energy:
    dims: [time]
    dtype: int32
    attrs:
      long_name: Transmit Energy
      standard_name: sound_pressure_level_of_acoustic_signal
      units: dB
  transmit_energy_bt:
    dims: [time_bt]
    dtype: int32
    attrs:
      long_name: Bottom Track Transmit Energy
      standard_name: sound_pressure_level_of_acoustic_signal
      units: dB
  transmit_energy_echo:
    dims: [time_echo]
    dtype: int32
    attrs:
      long_name: Echo Sounder Transmit Energy
      standard_name: sound_pressure_level_of_acoustic_signal
      units: dB
  error:
    dims: [time]
    dtype: int32
    attrs:
      long_name: Error Code
      units: "1"
  error_bt:
    dims: [time_bt]
    dtype: int32
    attrs:
      long_name: Bottom Track Error Code
      units: "1"
  error_echo:
    dims: [time_echo]
    dtype: int32
    attrs:
      long_name: Echo Sounder Error Code
      units: "1"
  ensemble:
    dims: [time]
    dtype: uint32
    attrs:
      units: count
      long_name: Ensemble Number
      standard_name: number_of_observations
  ensemble_bt:
    dims: [time_bt]
    dtype: uint32
    attrs:
      units: count
      long_name: Bottom Track Ensemble Number
      standard_name: number_of_observations
  ensemble_echo:
    dims: [time_echo]
    dtype: uint32
    attrs:
      units: count
      long_name: Echo Sounder Ensemble Number
      standard_name: number_of_observations
  status:
    dims: [time]
    dtype: uint32
    attrs:
      units: "1"
      long_name: Status Code
  status_bt:
    dims: [time_bt]
    dtype: uint32
    attrs:
      units: "1"
      long_name: Bottom Track Status Code
  status_echo:
    dims: [time_echo]
    dtype: uint32
    attrs:
      units: "1"
      long_name: Echo Sounder Status Code

  active_configuration:
    dims: [time]
    dtype: int32
    attrs:
      description: "Active configuration for instruments running a dual profile"
      units: "1"
  boost_running_flag:
    dims: [time]
    dtype: int32
    attrs:
      description: "Boost mode running (0 or 1)"
      units: "1"
  low_voltage_skip_flag:
    dims: [time]
    dtype: int32
    attrs:
      description: "Ping skipped due to low voltage (0 or 1)"
      units: "1"
  telemetry_data_flag:
    dims: [time]
    dtype: int32
    attrs:
      description: "Ping has associated telemetry data (0 or 1)"
      units: "1"

  latitude_gps:
    dims: [time_gps]
    dtype: float32
    attrs:
      units: deg N
      long_name: Latitude
      standard_name: latitude
  longitude_gps:
    dims: [time_gps]
    dtype: float32
    attrs:
      units: deg E
      long_name: Longitude
      standard_name: longitude
  vel_gps:
    dims: ["earth", "time_gps"]
    dtype: float32
    attrs:
      units: m/s
      long_name: Velocity from GPS
  fix_gps:
    dims: [time_gps]
    dtype: int8
    attrs:
      units: "1"
      long_name: GPS Fix
      standard_name: gps_fix_type
  n_sat_gps:
    dims: [time_gps]
    dtype: int8
    attrs:
      units: count
      long_name: Number of Satellites
      standard_name: number_of_satellites
  hdop_gps:
    dims: [time_gps]
    dtype: float32
    attrs:
      units: "1"
      long_name: HDOP
      standard_name: horizontal_dilution_of_precision
  elevation_gps:
    dims: [time_gps]
    dtype: float32
    attrs:
      units: m
      long_name: Elevation
      standard_name: elevation_above_MLLW
  speed_over_grnd_gps:
    dims: [time_gps]
    dtype: float32
    attrs:
      units: m/s
      long_name: Platform Speed
      standard_name: platform_speed_wrt_ground
  dir_over_grnd_gps:
    dims: [time_gps]
    dtype: float32
    attrs:
      units: degree
      long_name: Platform Course
      standard_name: platform_course
  heading_gps:
    dims: [time_gps]
    dtype: float32
    attrs:
      units: degree
      long_name: Platform Direction
      standard_name: platform_orientation
