classname: tsdat.io.retrievers.DefaultRetriever
parameters:
  merge_kwargs:
    combine_attrs: drop_conflicts
readers:
  .*:
    classname: tsdat.io.readers.ZipReader
    parameters:
      exclude: [".*\\.anpp", ".*\\.xml", ".*\\.~ed"]
      open_zip_kwargs:
        mode: rb
      read_zip_kwargs:
        mode: r
      readers:
        .*\.AD2CP:
          classname: pipelines.sigvm.readers.SigVMReader
          parameters:
            depth_offset: 0.5
            magnetic_declination: 15.6
        .*\.nmea:
          classname: pipelines.sigvm.readers.NMEAReader

coords:
  time:
    .*\.AD2CP:
      name: time
      # data_converters:
      #   - classname: tsdat.io.converters.StringToDatetime
      #     format: "%Y-%m-%dT%H:%M:%S"
      #     timezone: UTC
  time_bt:
    .*\.AD2CP:
      name: time_bt
      # data_converters:
      #   - classname: tsdat.io.converters.StringToDatetime
      #     format: "%Y-%m-%dT%H:%M:%S"
      #     timezone: UTC
  time_echo:
    .*\.AD2CP:
      name: time_echo
      # data_converters:
      #   - classname: tsdat.io.converters.StringToDatetime
      #     format: "%Y-%m-%dT%H:%M:%S"
      #     timezone: UTC
  time_gps:
    .*\.nmea:
      name: time_gps
  range:
    .*\.AD2CP:
      name: range
  range_echo:
    .*\.AD2CP:
      name: range_echo
  dir:
    .*\.AD2CP:
      name: dir
  inst:
    .*\.AD2CP:
      name: inst
  earth:
    .*\.AD2CP:
      name: earth

data_vars:
  vel:
    .*\.AD2CP:
      name: vel
  amp:
    .*\.AD2CP:
      name: amp
  corr:
    .*\.AD2CP:
      name: corr
  echo:
    .*\.AD2CP:
      name: echo

  vel_bt:
    .*\.AD2CP:
      name: vel_bt
  dist_bt:
    .*\.AD2CP:
      name: dist_bt
  fom_bt:
    .*\.AD2CP:
      name: fom_bt

  le_dist_alt:
    .*\.AD2CP:
      name: le_dist_alt
  le_quality_alt:
    .*\.AD2CP:
      name: le_quality_alt
  ast_dist_alt:
    .*\.AD2CP:
      name: ast_dist_alt
  ast_quality_alt:
    .*\.AD2CP:
      name: ast_quality_alt
  ast_offset_time_alt:
    .*\.AD2CP:
      name: ast_offset_time_alt
  pressure_alt:
    .*\.AD2CP:
      name: pressure_alt

  depth:
    .*\.AD2CP:
      name: depth
  heading:
    .*\.AD2CP:
      name: heading
  pitch:
    .*\.AD2CP:
      name: pitch
  roll:
    .*\.AD2CP:
      name: roll
  orientmat:
    .*\.AD2CP:
      name: orientmat
  beam2inst_orientmat:
    .*\.AD2CP:
      name: beam2inst_orientmat
  speed_of_sound:
    .*\.AD2CP:
      name: c_sound
  pressure:
    .*\.AD2CP:
      name: pressure
  temperature:
    .*\.AD2CP:
      name: temp

  transmit_energy:
    .*\.AD2CP:
      name: xmit_energy
  transmit_energy_bt:
    .*\.AD2CP:
      name: xmit_energy_bt
  transmit_energy_echo:
    .*\.AD2CP:
      name: xmit_energy_echo
  error:
    .*\.AD2CP:
      name: error
  error_bt:
    .*\.AD2CP:
      name: error_bt
  error_echo:
    .*\.AD2CP:
      name: error_echo
  ensemble:
    .*\.AD2CP:
      name: ensemble
  ensemble_bt:
    .*\.AD2CP:
      name: ensemble_bt
  ensemble_echo:
    .*\.AD2CP:
      name: ensemble_echo
  status:
    .*\.AD2CP:
      name: status
  status_bt:
    .*\.AD2CP:
      name: status_bt
  status_echo:
    .*\.AD2CP:
      name: status_echo

  active_configuration:
    .*\.AD2CP:
      name: active_config
  low_voltage_skip_flag:
    .*\.AD2CP:
      name: low_volt_skip
  boost_running_flag:
    .*\.AD2CP:
      name: boost_running
  telemetry_data_flag:
    .*\.AD2CP:
      name: telemetry_data

  latitude_gps:
    .*\.nmea:
      name: gga_lat
  longitude_gps:
    .*\.nmea:
      name: gga_lon
  fix_gps:
    .*\.nmea:
      name: gga_gps_qual
  n_sat_gps:
    .*\.nmea:
      name: gga_num_sats
  elevation_gps:
    .*\.nmea:
      name: gga_alt
  hdop_gps:
    .*\.nmea:
      name: gga_hdop
  dir_over_grnd_gps:
    .*\.nmea:
      name: vtg_course_deg
  speed_over_grnd_gps:
    .*\.nmea:
      name: vtg_spd_over_grnd_kt
  heading_gps:
    .*\.nmea:
      name: hdt_heading
