classname: tsdat.io.retrievers.DefaultRetriever
readers:
  .*:
    classname: tsdat.io.readers.ZipReader
    parameters:
      exclude: [".*\\.anpp", ".*\\.xml", ".*\\.~ed"]
      open_zip_kwargs:
        mode: rb
      read_zip_kwargs:
        mode: r
      readers:
        .*\.AD2CP:
          classname: pipelines.sigvm.readers.DownFacingADCPReader
          parameters:
            depth_offset: 0.5
            salinity: 30
            magnetic_declination: 15.6
        .*\.nmea:
          classname: pipelines.sigvm.readers.NMEAReader

coords:
  time:
    name: time
  time_bt:
    name: time_bt
  time_echo:
    name: time_echo
  range:
    name: range
  range_echo:
    name: range_echo
  dir:
    name: dir
  inst:
    name: inst
  earth:
    name: earth

data_vars:
  vel:
    name: vel
  vel_bt:
    name: vel_bt
  amp:
    name: amp
  corr:
    name: corr
  echo:
    name: echo
  dist_bt:
    name: dist_bt
  dist_alt:
    name: alt_dist
  dist_ast:
    name: ast_dist
  depth:
    name: depth
  water_density:
    name: water_density
  heading:
    name: heading
  pitch:
    name: pitch
  roll:
    name: roll
  orientmat:
    name: orientmat
  speed_of_sound:
    name: c_sound
  pressure_ast:
    name: ast_pressure
  offset_time_ast:
    name: ast_offset_time
  pressure:
    name: pressure
  temperature:
    name: temp
  transmit_energy:
    name: xmit_energy
  transmit_energy_bt:
    name: xmit_energy_bt
  transmit_energy_echo:
    name: xmit_energy_echo
  error:
    name: error
  error_bt:
    name: error_bt
  error_echo:
    name: error_echo
  quality_alt:
    name: alt_quality
  quality_ast:
    name: ast_quality
  active_configuration:
    name: active_config
  low_voltage_skip_flag:
    name: low_volt_skip
  boost_running_flag:
    name: boost_running
  telemetry_data_flag:
    name: telemetry_data
