classname: pipelines.up_looking_adcp.pipeline.UpLookingADCP

triggers:
  - .*\.ad2cp

retriever:
  path: pipelines/up_looking_adcp/config/retriever.yaml

dataset:
  path: pipelines/up_looking_adcp/config/dataset.yaml

quality:
  path: shared/quality.yaml
storage:
  path: shared/storage.yaml
