classname: tsdat.io.retrievers.DefaultRetriever
readers:
  .*:
    classname: pipelines.up_looking_adcp.readers.UpFacingADCPReader
    parameters:
      depth_offset: 0.5
      salinity: 30
      magnetic_declination: 15.6

coords:
  time:
    name: time
    data_converters:
      - classname: tsdat.io.converters.StringToDatetime
        format: "%Y-%m-%d %H:%M:%S"
        timezone: US/Pacific
  time_b5:
    name: time_b5
    data_converters:
      - classname: tsdat.io.converters.StringToDatetime
        format: "%Y-%m-%d %H:%M:%S"
        timezone: US/Pacific
  range:
    name: range
  range_b5:
    name: range_b5
  dir:
    name: dir
  inst:
    name: inst
  earth:
    name: earth
  q:
    name: q

data_vars:
  vel:
    name: vel
  vel_b5:
    name: vel_b5
  amp:
    name: amp
  corr:
    name: corr
  depth:
    name: depth
  water_density:
    name: water_density
  heading:
    name: heading
  pitch:
    name: pitch
  roll:
    name: roll
  quaternions:
    name: quaternions
  orientmat:
    name: orientmat
  speed_of_sound:
    name: c_sound
  pressure:
    name: pressure
  temperature:
    name: temp
